version: '3'
services:

  # this will start the database
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=contacts
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passwrd
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  # mongo database
  # db:
  #   image: mongo:4.1
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME: root
  #     - MONGO_INITDB_ROOT_PASSWORD: example

  # this will start my web server
  app:
    build:
      context: .
    restart: always
    environment:
      - POSTGRES_DATABASE=contacts
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passwrd
      - POSTGRES_PORT=5432
    volumes:
      - ./dist:/root/dist
      - ./server:/root/server
    ports:
      - 3000:3000

